### ISSUE TITLE
مشکل در کانفیگ وبسرویس

### ISSUE THREAD

**Issue by sircommand** [nevisa-team/nevisa-doc#6]
```
nevisa/set_config

{
    "id": "-",
    "service_account": -,
    "show_word_confidences": true,
    "telegram_english": false,
    "save_transcriptions": true,
    "convert_punctuations": true,
    "convert_numbers": true,
    "show_digits_in_english": true,
    "add_number_separator": true
}
```
چرا پس تو متد celery-progress هنوز داره خروجی حرف برمیگردونه، یعنی عدد نمیشه؟
```
                {
                    "conf": 1.0,
                    "end": 3.42,
                    "start": 3.09,
                    "word": "دويست",
                    "space_after": true
                },
```
اون "دویست" طبیعتا وقتی  "convert_numbers": true, هست باید میشد 200 اما هنوز حرف هست
https://github.com/nevisa-team/w2ni18n/blob/master/python/unit_testing_fa.py
اینجا هم به زبان پایتون یه کد تبدیل نوشتین در صورتی که طبیعتا باید خود وبسرویس با همون ست کانفیگ تو متد celery-progress تبدیل به عدد رو انجام میداد

چطوری این مشکل حل میشه؟

**Comment by gooran** [comment]
سلام
خیر سمت بک‌اند ما تبدیل اعداد را انجام نمی‌دهیم. از `convert_numbers `فقط برای ذخیره وضعیت استفاده می‌شود.
تبدیل متن به عدد در حال حاضر در سمت فرانت انجام می شود. برای تبدیل اعداد فارسی در پایتون می توانید از کتابخانه زیر استفاده کنید:

https://github.com/nevisa-team/w2ni18n/tree/master/python

**Comment by sircommand** [comment]
سلام
اینو قبلا دیده بودم ، پس این قابلیت تو پارامترهای متد  celery-progress وجود نداره 
ایا این اضافه میشه یا قرار نیست اضافه بشه؟
اون کد پایتون رو دیدم اپ جاوا هست میشه برای کانورت نوشت منتهی خب رو وبسرویس بود استیبل بود هم سرعتش بهتر بود

**Comment by gooran** [comment]
بله در نسخه‌های بعدی اضافه می‌شود.
